# Config file master for Migrator.

fetch:  # Settings for your old server
    base-url: http://hubzilla  # What it says. You can include a http://host:port too.
    pw: test  
    login: test
    insecure: false # Set this to true if you are running SNI (more than one SSL cert on the same server    max-retries:  10  # How many times to retry on a transient network error.
    retry-wait: 5000  # How long (milliseconds) to wait between retries.  Algorithm will double this every time.
    socket-timeout: 120000  #Timeout (ms) waiting for a socket to open.  If the server is slow, set longer.
    conn-timeout: 20000 # How long (ms) to wait for a connection to the server.

push:  # Settings for your NEW server. Logins and passwords can be different.
    base-url: http://anotherhubzilla  # This had better be a different URL than your old server!
    pw: test
    login: test
    max-retries:  10
    insecure: false # Set this to true if you are running SNI (more than one SSL cert on the same server)
    seize: false # Relevant only for push. Will take control of the imported channels from other hubs
    socket-timeout: 120000
    conn-timeout: 20000
    retry-wait: 5000

storage: # Where to save the JSON files. This must be readable and writable.
    save-directory: /mnt/sdcard/tmp/out


log:  # Logging configuration
    spit-filename: migrator.log4j  # Where to save the log.
    level: info  # By default, log only necessary things. Other levels are warn, debug, and trace.
