fetch:
    base-url: http://hubzilla
    pw: test
    login: testes

push:
    base-url: http://anotherhubzilla
    pw: test
    login: testes
    seize: false

storage:
    save-directory: /mnt/sdcard/tmp/out
